import type { Metadata } from "next"
import { inter, notoSans, openSans, poppins } from "@/fonts"

import "@/styles/globals.css"

import AppProvider from "@/providers/AppProvider"
import { cn } from "@/utils/helper"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          notoSans.variable,
          openSans.variable,
          poppins.variable,
          inter.variable,
          "antialiased",
        )}>
        <AppProvider>
          <main className="font-noto-sans bg-black-primary min-h-screen w-full text-white">
            {children}
          </main>
        </AppProvider>
      </body>
    </html>
  )
}
